name: flutter_application
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  desktop_window: ^0.4.0
  flutter:
    sdk: flutter
  flutter_bluetooth_serial: ^0.4.0
  # flutter_localization: ^0.2.0
  permission_handler: ^11.0.1
  syncfusion_flutter_charts: ^25.1.41+2
  syncfusion_localizations: ^25.1.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
